library(readxl)
LabTATT <- read_excel("C:/Users/Rafiya/Downloads/LabTATT.xlsx")
 View(LabTATT)
attach(LabTATT)
boxplot(LabTATT)
shapiro.test(`Laboratory 1`)
shapiro.test(`Laboratory 2`)
shapiro.test(`Laboratory 3`)
Stacked_Data <- stack(LabTATT)
View(Stacked_Data)
attach(Stacked_Data)
boxplot(Stacked_Data)
bartlett.test(values~ind, data=Stacked_Data) 
Anova_results <- aov(values~ind,data = Stacked_Data)
summary(Anova_results)
# accept null hypothesis 